# -  /254gerboo/

FROM quay.io/254gerboo/tribal-chief
RUN git clone https://github.com/254gerboo/tribal-chief-Md /root/tribal-chief
WORKDIR /root/tribal-chief/
RUN npm install
EXPOSE 8000
CMD ["npm","start","yarn" ]
  
# -  /254gerboo/
 